export const catConsts = {
    CATEGORY_FETCH_REQUEST: 'CATEGORY_FETCH_REQUEST',
    CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
    CATEGORY_FETCH_FAILED: 'CATEGORY_FETCH_FAILED',
    CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
    CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
    CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
    GET_CAT_BY_SLUG_SUCCESS: 'GET_CAT_BY_SLUG_SUCCESS',
    FETCH_CATEGORY_PATH_SUCCESS: 'FETCH_CATEGORY_PATH_SUCCESS'
}

export const productListConsts = {
  PRODUCTLIST_FETCH_REQUEST: "PRODUCTLIST_FETCH_REQUEST",
  PRODUCTLIST_FETCH_SUCCESS: "PRODUCTLIST_FETCH_SUCCESS",
  PRODUCTLIST_FETCH_FAILED: "PRODUCTLIST_FETCH_FAILED",
  GET_PRODUCTLIST_BY_FILTER_REQUEST: "GET_PRODUCTLIST_BY_FILTER_REQUEST",
  GET_PRODUCTLIST_BY_FILTER_SUCCESS: "GET_PRODUCTLIST_BY_FILTER_SUCCESS",
  GET_PRODUCTLIST_BY_FILTER_FAILURE: "GET_PRODUCTLIST_BY_FILTER_FAILURE",
};
export const authConsts = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FALIURE: "LOGIN_FALIURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
};

export const productConstants = {
  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",
  PRODUCT_FETCH_REQUEST: 'PRODUCT_FETCH_REQUEST',
  PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
  PRODUCT_FETCH_FAILED: 'PRODUCT_FETCH_FAILED',
};

export const initDataConsts = {
  INIT_DATA_FETCH_REQUEST: 'INIT_DATA_FETCH_REQUEST',
  INIT_DATA_FETCH_SUCCESS: 'INIT_DATA_FETCH_SUCCESS',
  INIT_DATA_FETCH_FAILED: 'INIT_DATA_FETCH_FAILED'
};

export const cartConstants = {
  
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",

};

export const userConstants = {
  GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
  GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
  GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
  ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
  ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
  GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
  GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
};